/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DOMAIN.User;
import GUI.Groups.GroupsForm;
import GUI.Journal.JournalForm;
import GUI.Students.StudentsForm;
import GUI.Subjects.SubjectForm;
import GUI.Teachers.TeachersForm;


/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {
    
    /**
     * Creates new form LoginForm
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        groups = new javax.swing.JButton();
        teachers = new javax.swing.JButton();
        subjects = new javax.swing.JButton();
        students = new javax.swing.JButton();
        groups1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        groups2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        groups3 = new javax.swing.JButton();
        groups4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(520, 250));
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        groups.setBackground(new java.awt.Color(255, 255, 255));
        groups.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        groups.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupsActionPerformed(evt);
            }
        });
        jPanel3.add(groups, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 70, 60));

        teachers.setBackground(new java.awt.Color(255, 255, 255));
        teachers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/male-cartoon-pointing-to-white-board.png"))); // NOI18N
        teachers.setBorder(null);
        teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teachersActionPerformed(evt);
            }
        });
        jPanel3.add(teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 140, 130));

        subjects.setBackground(new java.awt.Color(255, 255, 255));
        subjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/books-stack.png"))); // NOI18N
        subjects.setBorder(null);
        subjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectsActionPerformed(evt);
            }
        });
        jPanel3.add(subjects, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 140, 130));

        students.setBackground(new java.awt.Color(255, 255, 255));
        students.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graduate-student-avatar.png"))); // NOI18N
        students.setBorder(null);
        students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsActionPerformed(evt);
            }
        });
        jPanel3.add(students, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 130));

        groups1.setBackground(new java.awt.Color(255, 255, 255));
        groups1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/newspaper.png"))); // NOI18N
        groups1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groups1ActionPerformed(evt);
            }
        });
        jPanel3.add(groups1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 140, 130));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Предмети");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 133, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Вийти");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 70, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Викладачі");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 140, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Студенти");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Журнал успішності");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 190, -1));

        groups2.setBackground(new java.awt.Color(255, 255, 255));
        groups2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/classroom (1).png"))); // NOI18N
        groups2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groups2ActionPerformed(evt);
            }
        });
        jPanel3.add(groups2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 130));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Групи");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 140, -1));

        groups3.setBackground(new java.awt.Color(255, 255, 255));
        groups3.setForeground(new java.awt.Color(0, 51, 255));
        groups3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/settings.png"))); // NOI18N
        groups3.setText("Налаштування");
        groups3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groups3ActionPerformed(evt);
            }
        });
        jPanel3.add(groups3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 150, 40));

        groups4.setBackground(new java.awt.Color(255, 255, 255));
        groups4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/reload-symbol.png"))); // NOI18N
        groups4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groups4ActionPerformed(evt);
            }
        });
        jPanel3.add(groups4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 70, 60));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 153, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Оновити");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 90, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 255));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/home (1).png"))); // NOI18N

        jLabel7.setBackground(new java.awt.Color(0, 51, 255));
        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Головна сторінка");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupsActionPerformed
        System.exit(0);
    }//GEN-LAST:event_groupsActionPerformed

    private void teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teachersActionPerformed
        this.setVisible(false);
        new TeachersForm().setVisible(true);
    }//GEN-LAST:event_teachersActionPerformed

    private void subjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectsActionPerformed
        this.setVisible(false);
        new SubjectForm().setVisible(true);
    }//GEN-LAST:event_subjectsActionPerformed

    private void studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsActionPerformed
        this.setVisible(false);
        new StudentsForm().setVisible(true);
    }//GEN-LAST:event_studentsActionPerformed

    private void groups1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groups1ActionPerformed
        new JournalForm().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_groups1ActionPerformed

    private void groups2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groups2ActionPerformed
        this.setVisible(false);
        new GroupsForm().setVisible(true);
    }//GEN-LAST:event_groups2ActionPerformed

    private void groups3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groups3ActionPerformed
        new Option().setVisible(true);
    }//GEN-LAST:event_groups3ActionPerformed

    private void groups4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groups4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_groups4ActionPerformed

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        if(evt.isPopupTrigger())
        {
           // contexMenu.show(this, evt.getX() + 170, evt.getY() + 65);
        }
    }//GEN-LAST:event_jPanel3MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton groups;
    private javax.swing.JButton groups1;
    private javax.swing.JButton groups2;
    private javax.swing.JButton groups3;
    private javax.swing.JButton groups4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton students;
    private javax.swing.JButton subjects;
    private javax.swing.JButton teachers;
    // End of variables declaration//GEN-END:variables
}
