/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Students;

import GUI.MainForm;
import GUI.Teachers.TeachersForm;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.print.PrinterException;
import java.io.BufferedWriter;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import DOMAIN.Student;
import GUI.Main;

/**
 *
 * @author Admin
 */
public class StudentsForm extends javax.swing.JFrame {
    static Socket socketConnection;
    String path = "not found";
    DefaultTableModel dtm = new DefaultTableModel();
    int studID = 0;
    
    public StudentsForm() {
        initComponents();
        dtm.addColumn("ID");
        dtm.addColumn("Прізвище");
        dtm.addColumn("Ім'я");
        dtm.addColumn("Форма навчання");
        dtm.addColumn("№ залікової книжки");
        jTable1.setModel(dtm);
        
        jTable1.getTableHeader().addMouseListener(new MouseAdapter() {public void mouseClicked(MouseEvent e) {
            int col = jTable1.columnAtPoint(e.getPoint());
            String sortCol = "";
            switch (col) {
                case 0:
                    sortCol = "studentID";
                    break;
                case 1:
                    sortCol = "studentLastname";
                    break;
                case 2:
                    sortCol = "studentFirstName";
                    break;
                case 3:
                    sortCol = "studentFormOfStudy";
                    break;
                case 4:
                    sortCol = "studentNumberOfRecordBook";
                    break;
                default: sortCol = "studentID";
                    break;
            }
            sortStudents(sortCol);
        }});
        jTable1.addMouseListener(new MouseAdapter(){
            public void mousePressed(MouseEvent me){
                me.getSource();
                Point point = me.getPoint();
                int row = jTable1.rowAtPoint(point);
                if(me.getClickCount() == 2){
                    new EditStudent((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0)).setVisible(true);  
                    closeForm();
                }
            }
        });
        displayStudents();      
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jTextField8 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTextField10 = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel17 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JToolBar.Separator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JToolBar.Separator();
        jLabel18 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        jLabel24 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        jLabel23 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JToolBar.Separator();
        jLabel20 = new javax.swing.JLabel();

        jMenuItem1.setText("Додати");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("Редагувати");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setText("Видалити");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem3MouseClicked(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem7.setText("Зберегти");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem7);

        jMenuItem4.setText("Оцінки");
        jMenuItem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem4MouseClicked(evt);
            }
        });
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem4);

        jMenuItem6.setText("Друк");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem6);

        jMenuItem5.setText("Закрити");
        jMenuItem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem5MouseClicked(evt);
            }
        });
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(450, 250));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 255));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Список студентів");

        jLabel2.setBackground(new java.awt.Color(0, 51, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/graduate-student-avatar1.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(0, 51, 255));
        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error.png"))); // NOI18N
        jLabel3.setText("Закрити");
        jLabel3.setToolTipText("");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(167, 167, 167)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 370));

        jLabel4.setBackground(new java.awt.Color(0, 51, 255));
        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("По-батькові");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 51, 255));
        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 255));
        jLabel5.setText("Прізвище");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 51, 255));
        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Ім'я");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 51, 255));
        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("Група");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 51, 255));
        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("№ залікової книжки");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 51, 255));
        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Форма навчання");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 51, 255));
        jLabel10.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("Тип навчання");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, -1, -1));

        jLabel11.setBackground(new java.awt.Color(0, 51, 255));
        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Дата народження");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 51, 255));
        jLabel12.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 255));
        jLabel12.setText("Стать");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 51, 255));
        jLabel13.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 255));
        jLabel13.setText("Адреса");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, -1, -1));

        jLabel14.setBackground(new java.awt.Color(0, 51, 255));
        jLabel14.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 255));
        jLabel14.setText("Телефон");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(null);
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 170, 20));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(null);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 40, 160, 20));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setBorder(null);
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 160, 20));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(null);
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 160, 20));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));
        jPanel3.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 100, 20));

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jTextField6.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField6.setBorder(null);
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 170, 20));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/add-contact.png"))); // NOI18N
        jButton2.setText("Додати");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, 140, 30));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/delete.png"))); // NOI18N
        jButton4.setText("Видалити");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 140, 30));

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setBorder(null);
        jPanel3.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 160, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator1.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator1.setOpaque(true);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 160, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator2.setOpaque(true);
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 160, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator3.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator3.setOpaque(true);
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 160, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator4.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator4.setOpaque(true);
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 170, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator5.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator5.setOpaque(true);
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 160, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator6.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator6.setOpaque(true);
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 120, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator7.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator7.setOpaque(true);
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 170, -1));

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(255, 255, 255));
        jTextField8.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setBorder(null);
        jPanel3.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 120, 20));

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 140, 150));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/pencil (2).png"))); // NOI18N
        jButton5.setText("Редагувати");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 140, 30));

        jSeparator8.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator8.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator8.setOpaque(true);
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 120, -1));

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 255));
        jTextField9.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setBorder(null);
        jPanel3.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 120, 20));

        jSeparator9.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator9.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator9.setOpaque(true);
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 120, -1));

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 255));
        jTextField10.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setBorder(null);
        jPanel3.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 120, 20));

        jSeparator10.setBackground(new java.awt.Color(0, 51, 255));
        jSeparator10.setForeground(new java.awt.Color(0, 51, 255));
        jSeparator10.setOpaque(true);
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 120, -1));

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 255));
        jTextField11.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setBorder(null);
        jPanel3.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 120, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/note.png"))); // NOI18N
        jButton1.setText("Оцінки");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 140, 30));

        jLabel21.setBackground(new java.awt.Color(0, 51, 255));
        jLabel21.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel21.setText("Швидкий пошук");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jTextField12.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField12KeyReleased(evt);
            }
        });
        jPanel3.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 190, 20));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/reload (1).png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 40, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/magnifying-glass (1).png"))); // NOI18N
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 4, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 740, 370));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/plus-symbol-in-a-rounded-black-square.png"))); // NOI18N
        jLabel17.setToolTipText("Додати студента");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel17);
        jToolBar1.add(jSeparator11);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/edit-interface-sign.png"))); // NOI18N
        jLabel16.setToolTipText("Редагувати дані студента");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel16);
        jToolBar1.add(jSeparator12);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/exit.png"))); // NOI18N
        jLabel18.setToolTipText("Видалити студента");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel18);
        jToolBar1.add(jSeparator13);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/notes.png"))); // NOI18N
        jLabel19.setToolTipText("Оцінки студента");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel19);
        jToolBar1.add(jSeparator14);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/save.png"))); // NOI18N
        jLabel24.setToolTipText("Зберегти");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel24);
        jToolBar1.add(jSeparator15);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/printer-.png"))); // NOI18N
        jLabel23.setToolTipText("Друк");
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel23);
        jToolBar1.add(jSeparator16);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png/reload.png"))); // NOI18N
        jLabel20.setToolTipText("Оновити дані");
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        jToolBar1.add(jLabel20);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 740, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void closeForm(){
        this.setVisible(false);
    }
    public void Search(String query){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dtm);
        jTable1.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    private void sortStudents(String column){
        dtm.getDataVector().removeAllElements();
        ArrayList<Student> student = new  ArrayList<Student>();
        try {
            socketConnection = new Socket("127.0.0.1", 11111);
            DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
            String SQL = "sortStudents";
            outToServer.writeUTF(SQL);
        } catch (IOException e) {System.out.println(e); }
        try {
            DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
           // int SQL = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            outToServer.writeUTF(column);
        } catch (IOException e) {System.out.println(e); }
         try {
                ObjectInputStream objectInput = new ObjectInputStream(socketConnection.getInputStream());
                try {
                    student = (ArrayList<Student>) objectInput.readObject();
                    for(int i = 0; i < student.size(); i++){
                        dtm.addRow(new Object[]{student.get(i).getStudentId(),student.get(i).getLastName(),
                                    student.get(i).getFirstName(), student.get(i).getStudyForm(), 
                                    student.get(i).getZalikCardNumber()});
                    }

                } catch (ClassNotFoundException e) {
                    System.out.println("The title list has not come from the server");
                }
            } catch (IOException e) {
                System.out.println("The socket for reading the object has problem");
            }
        
    }
    
    private void displayStudents(){
        dtm.getDataVector().removeAllElements();
        ArrayList<Student> allStudents = new  ArrayList<Student>();
        try {
             socketConnection = new Socket("127.0.0.1", 11111);
            DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
            String SQL = "getAllStudents";
            outToServer.writeUTF(SQL);
        } catch (Exception e) {System.out.println(e); }
         try {
                ObjectInputStream objectInput = new ObjectInputStream(socketConnection.getInputStream());
                try {
                    allStudents = (ArrayList<Student>) objectInput.readObject();
                    for(int i = 0; i < allStudents.size(); i++)
                    {
                        dtm.addRow(new Object[]{allStudents.get(i).getStudentId(),
                        allStudents.get(i).getLastName(), allStudents.get(i).getFirstName(),
                        allStudents.get(i).getStudyForm(), allStudents.get(i).getZalikCardNumber()});
                    }
                } catch (ClassNotFoundException e) {
                    System.out.println("The title list has not come from the server");
                    e.printStackTrace();
                }
            } catch (IOException e) {
                System.out.println("The socket for reading the object has problem");
                e.printStackTrace();
            } 
    }
    
    
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Main().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        studID = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        ArrayList<Student> student = new  ArrayList<Student>();
        try {
            socketConnection = new Socket("127.0.0.1", 11111);
            DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
            String SQL = "getStudent";
            outToServer.writeUTF(SQL);
        } catch (IOException e) {System.out.println(e); }
        try {
            DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
            int SQL = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
            outToServer.writeInt(SQL);
        } catch (IOException e) {System.out.println(e); }
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
         try {
                ObjectInputStream objectInput = new ObjectInputStream(socketConnection.getInputStream());
                try {
                    student = (ArrayList<Student>) objectInput.readObject();

                        jTextField2.setText(student.get(0).getLastName());
                        jTextField3.setText(student.get(0).getFirstName());
                        jTextField4.setText(student.get(0).getForeName());
                        jTextField7.setText(student.get(0).getGroupName());
                        jTextField5.setText(student.get(0).getZalikCardNumber());
                        jTextField8.setText(student.get(0).getBirthdate());
                        jTextField9.setText(student.get(0).getStudyForm());
                        jTextField10.setText(student.get(0).getStudyType());
                        jTextField1.setText(student.get(0).getPhone());
                        jTextField11.setText(student.get(0).getSex());
                        jTextField6.setText(student.get(0).getAddress());
                        ImageIcon image = new ImageIcon(new ImageIcon(student.get(0).getFoto()).getImage());
                        jLabel15.setIcon(image);

                } catch (ClassNotFoundException e) {
                    System.out.println("The title list has not come from the server");
                }
            } catch (IOException e) {
                System.out.println("The socket for reading the object has problem");
            }
         path = student.get(0).getFotoUrl();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        NewStudent newS = new NewStudent();
        newS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     if(studID == 0){
          JOptionPane.showMessageDialog(this, "Виберіть, будь ласка, студента зі списку!");
     }
     else{
        int s = JOptionPane.showConfirmDialog(
            null,
            "Видалити цього студента?",
            "An Inane Question",
            JOptionPane.YES_NO_OPTION);

        if(s == JOptionPane.YES_OPTION){
            try {
                socketConnection = new Socket("127.0.0.1", 11111);
                DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
                String SQL = "deleteStudent";
                outToServer.writeUTF(SQL);
            } catch (IOException e) {System.out.println(e); }
            try {
                DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
                int SQL = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                outToServer.writeInt(SQL);
            } catch (IOException e) {System.out.println(e); }
            JOptionPane.showMessageDialog(null, "Студента видалено!");
            displayStudents();
            studID = 0;
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       if(studID == 0){
           JOptionPane.showMessageDialog(this, "Виберіть, будь ласка, студента зі списку!");
       }
       else{
            new EditStudent((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0)).setVisible(true);
            this.setVisible(false);
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //displayStudents();
    }//GEN-LAST:event_formWindowActivated

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        studID = 0;
        displayStudents();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(studID == 0){
           JOptionPane.showMessageDialog(this, "Виберіть, будь ласка, студента!");
       }
       else{
        new StudentNotes((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0),(String) jTable1.getValueAt(jTable1.getSelectedRow(), 1),(String) jTable1.getValueAt(jTable1.getSelectedRow(),2)).setVisible(true);
        this.setVisible(false);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyReleased
        Search(jTextField12.getText());
    }//GEN-LAST:event_jTextField12KeyReleased

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased
        if(evt.isPopupTrigger())
        {
            jPopupMenu1.show(this, evt.getX(), evt.getY() + 80);
        }
    }//GEN-LAST:event_jPanel3MouseReleased

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        NewStudent newS = new NewStudent();
        newS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
       if(studID == 0){
           JOptionPane.showMessageDialog(this, "Виберіть, будь ласка, студента зі списку!");
       }
       else{
            new EditStudent((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0)).setVisible(true);
            this.setVisible(false);
       }
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        if(studID == 0){
          JOptionPane.showMessageDialog(this, "Виберіть, будь ласка, студента зі списку!");
     }
     else{
        int s = JOptionPane.showConfirmDialog(
            null,
            "Видалити цього студента?",
            "An Inane Question",
            JOptionPane.YES_NO_OPTION);

        if(s == JOptionPane.YES_OPTION){
            try {
                socketConnection = new Socket("127.0.0.1", 11111);
                DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
                String SQL = "deleteStudent";
                outToServer.writeUTF(SQL);
            } catch (IOException e) {System.out.println(e); }
            try {
                DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
                int SQL = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                outToServer.writeInt(SQL);
            } catch (IOException e) {System.out.println(e); }
            JOptionPane.showMessageDialog(null, "Студента видалено!");
            displayStudents();
            studID = 0;
            }
        }
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        if(studID == 0){
           JOptionPane.showMessageDialog(this, "Виберіть, будь ласка, студента!");
       }
       else{
        new StudentNotes((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0),(String) jTable1.getValueAt(jTable1.getSelectedRow(), 1),(String) jTable1.getValueAt(jTable1.getSelectedRow(),2)).setVisible(true);
        this.setVisible(false);
       }
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        displayStudents();
    }//GEN-LAST:event_jLabel20MouseClicked

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
    
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
       
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MouseClicked
         
    }//GEN-LAST:event_jMenuItem3MouseClicked

    private void jMenuItem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem4MouseClicked
       
    }//GEN-LAST:event_jMenuItem4MouseClicked

    private void jMenuItem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem5MouseClicked
       new MainForm().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jMenuItem5MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        NewStudent newS = new NewStudent();
        newS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(studID == 0){
           JOptionPane.showMessageDialog(this, "Виберіть, будь ласка, студента зі списку!");
       }
       else{
            new EditStudent((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0)).setVisible(true);
            this.setVisible(false);
       }        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if(studID == 0){
          JOptionPane.showMessageDialog(this, "Виберіть, будь ласка, студента зі списку!");
     }
     else{
        int s = JOptionPane.showConfirmDialog(
            null,
            "Видалити цього студента?",
            "An Inane Question",
            JOptionPane.YES_NO_OPTION);

        if(s == JOptionPane.YES_OPTION){
            try {
                socketConnection = new Socket("127.0.0.1", 11111);
                DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
                String SQL = "deleteStudent";
                outToServer.writeUTF(SQL);
            } catch (IOException e) {System.out.println(e); }
            try {
                DataOutputStream outToServer = new DataOutputStream(socketConnection.getOutputStream());
                int SQL = (int) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
                outToServer.writeInt(SQL);
            } catch (IOException e) {System.out.println(e); }
            JOptionPane.showMessageDialog(null, "Студента видалено!");
            displayStudents();
            studID = 0;
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         if(studID == 0){
           JOptionPane.showMessageDialog(this, "Виберіть, будь ласка, студента!");
       }
       else{
        new StudentNotes((int) jTable1.getValueAt(jTable1.getSelectedRow(), 0),(String) jTable1.getValueAt(jTable1.getSelectedRow(), 1),(String) jTable1.getValueAt(jTable1.getSelectedRow(),2)).setVisible(true);
        this.setVisible(false);
       }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        MessageFormat header = new MessageFormat("Список студентів");
        MessageFormat footer = new MessageFormat("Page(0,number,integer)");
        try{
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(TeachersForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        MessageFormat header = new MessageFormat("Список викладачів коледжу");
        MessageFormat footer = new MessageFormat("Page(0,number,integer)");
        try{
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (PrinterException ex) {
            Logger.getLogger(TeachersForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        FileWriter fw = null;
        File file = new File("Список студентів.txt");
        if(!file.exists()){
             try {
                 file.createNewFile();
             } catch (IOException ex) {
                 Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
             }    
        }
        try {
            fw = new FileWriter(file.getAbsoluteFile());
        } catch (IOException ex) {
            Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        BufferedWriter bw = new BufferedWriter(fw);
        for(int i = 0; i < jTable1.getRowCount(); i++){
            for(int j = 0; j < jTable1.getColumnCount(); j++){
                
                try {
                    bw.write(jTable1.getModel().getValueAt(i, j) + " ");
                } catch (IOException ex) {
                    Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
                }   
            }
             try {
                 bw.newLine();
             } catch (IOException ex) {
                 Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
       
        try {
            bw.newLine();
            bw.write("Дата збереження: " + dateFormat.format(date).toString());
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Дані збережено у файл!");
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FileWriter fw = null;
        File file = new File("Список студентів.txt");
        if(!file.exists()){
             try {
                 file.createNewFile();
             } catch (IOException ex) {
                 Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
             }    
        }
        try {
            fw = new FileWriter(file.getAbsoluteFile());
        } catch (IOException ex) {
            Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        BufferedWriter bw = new BufferedWriter(fw);
        for(int i = 0; i < jTable1.getRowCount(); i++){
            for(int j = 0; j < jTable1.getColumnCount(); j++){
                
                try {
                    bw.write(jTable1.getModel().getValueAt(i, j) + " ");
                } catch (IOException ex) {
                    Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
                }   
            }
             try {
                 bw.newLine();
             } catch (IOException ex) {
                 Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        Date date = new Date();
       
        try {
            bw.newLine();
            bw.write("Дата збереження: " + dateFormat.format(date).toString());
            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(StudentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Дані збережено у файл!");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator11;
    private javax.swing.JToolBar.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JToolBar.Separator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
